/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransportType = IDL.Variant({
  'train' : IDL.Null,
  'flight' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingType = IDL.Variant({
  'train' : IDL.Null,
  'flight' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'transportOptionId' : IDL.Opt(IDL.Nat),
  'bookingType' : BookingType,
  'details' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Destination = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const TransportOption = IDL.Record({
  'id' : IDL.Nat,
  'destinationId' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'transportType' : TransportType,
  'schedule' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransportOption' : IDL.Func(
      [IDL.Nat, TransportType, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [BookingType, IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getBookingById' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByCaller' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDestinationById' : IDL.Func([IDL.Nat], [Destination], ['query']),
  'getDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getTransportOptionById' : IDL.Func([IDL.Nat], [TransportOption], ['query']),
  'getTransportOptionsByDestination' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TransportOption)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransportType = IDL.Variant({
    'train' : IDL.Null,
    'flight' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingType = IDL.Variant({ 'train' : IDL.Null, 'flight' : IDL.Null });
  const ContactInquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'transportOptionId' : IDL.Opt(IDL.Nat),
    'bookingType' : BookingType,
    'details' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Destination = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const TransportOption = IDL.Record({
    'id' : IDL.Nat,
    'destinationId' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'transportType' : TransportType,
    'schedule' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransportOption' : IDL.Func(
        [IDL.Nat, TransportType, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [BookingType, IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getBookingById' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByCaller' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDestinationById' : IDL.Func([IDL.Nat], [Destination], ['query']),
    'getDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getTransportOptionById' : IDL.Func(
        [IDL.Nat],
        [TransportOption],
        ['query'],
      ),
    'getTransportOptionsByDestination' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TransportOption)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };