/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'transportOptionId' : [] | [bigint],
  'bookingType' : BookingType,
  'details' : string,
}
export type BookingType = { 'train' : null } |
  { 'flight' : null };
export interface ContactInquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Destination {
  'id' : bigint,
  'latitude' : number,
  'country' : string,
  'city' : string,
  'name' : string,
  'description' : string,
  'longitude' : number,
}
export interface TransportOption {
  'id' : bigint,
  'destinationId' : bigint,
  'availableSeats' : bigint,
  'transportType' : TransportType,
  'schedule' : string,
}
export type TransportType = { 'train' : null } |
  { 'flight' : null };
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTransportOption' : ActorMethod<
    [bigint, TransportType, string, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[BookingType, string, bigint, bigint], bigint>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getBookingById' : ActorMethod<[bigint], Booking>,
  'getBookingsByCaller' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDestinationById' : ActorMethod<[bigint], Destination>,
  'getDestinations' : ActorMethod<[], Array<Destination>>,
  'getTransportOptionById' : ActorMethod<[bigint], TransportOption>,
  'getTransportOptionsByDestination' : ActorMethod<
    [bigint],
    Array<TransportOption>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactInquiry' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];